[package]
name = "zcash"
version = "0.6.0"
authors = [
    "Collin Chin",
    "Raymond Chu",
    "Ali Mousa",
    "Howard Wu"
]
description = "A library for generating Zcash wallets"
homepage = "https://github.com/ArgusHQ/wagu"
repository = "https://github.com/ArgusHQ/wagu"
categories = ["command-line-utilities"]
keywords = ["cryptocurrency", "blockchain", "bitcoin", "wallet", "ethereum"]
readme = "README.md"
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
wagu-model = { path = "../model" }

pairing = {  git = "https://github.com/ArgusHQ/librustzcash", branch = "master" }
sapling-crypto = {  git = "https://github.com/ArgusHQ/librustzcash", branch = "master" }
zcash_primitives = {  git = "https://github.com/ArgusHQ/librustzcash", branch = "master" }

bech32 = { version = "0.6" }
base58 = { version = "0.1" }
hex = { version = "0.3.2" }
rand = { version = "0.7" }
ripemd160 = { version = "0.7" }
secp256k1 = { version = "0.15.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
sha2 = { version = "0.7" }

[badges]
travis-ci = { repository = "ArgusHQ/wagu", branch = "master" }
