[package]
name = "zcash"
version = "0.6.0"
authors = [
    "Collin Chin",
    "Raymond Chu",
    "Ali Mousa",
    "Howard Wu"
]
description = "A library for generating Zcash wallets"
homepage = "https://github.com/ArgusHQ/wagyu"
repository = "https://github.com/ArgusHQ/wagyu"
categories = ["command-line-utilities"]
keywords = ["cryptocurrency", "blockchain", "bitcoin", "wallet", "ethereum"]
readme = "README.md"
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
wagyu-model = { path = "../model" }

pairing = {  git = "https://github.com/ArgusHQ/librustzcash", branch = "master" }
sapling-crypto = {  git = "https://github.com/ArgusHQ/librustzcash", branch = "master" }
zcash_primitives = {  git = "https://github.com/ArgusHQ/librustzcash", branch = "master" }

bech32 = { version = "0.6" }
base58 = { version = "0.1" }
byteorder = { version = "1.1" }
curve25519-dalek = { version = "1" }
hex = { version = "0.3.2" }
rand = { version = "0.7" }
rand_core = { version = "0.5.0" }
rust-crypto = { version = "0.2" }
ripemd160 = { version = "0.7" }
secp256k1 = { version = "0.15.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

[badges]
travis-ci = { repository = "ArgusHQ/wagyu", branch = "master" }
